SELECT c.ID, c.NAME, COUNT(r.ID) AS NUM_RECORDS, TO_CHAR(r.OPEN_DATE, 'DD.MM.YYYY') AS DATE_
FROM RECORDS r
JOIN ACCOUNTS a ON r.ACC_REF = a.ID 
JOIN CLIENTS c ON a.CLIENT_REF = c.ID
WHERE ADD_MONTHS(r.OPEN_DATE, 1) > CURRENT_DATE
GROUP BY r.OPEN_DATE , c.ID, c.NAME
ORDER BY r.OPEN_DATE , c.NAME;