SELECT a.* , pt1.NAME ,pt2.NAME
FROM ACCOUNTS a 
JOIN PRODUCTS p1 ON a.PRODUCT_REF = p1.ID 
JOIN PRODUCTYPE pt1 ON p1.PRODUCT_TYPE_ID = pt1.ID 
JOIN CLIENTS c ON  a.CLIENT_REF  = c.ID
JOIN PRODUCTS p2 ON c.ID  = p2.CLIENT_REF AND a.PRODUCT_REF != p2.ID 
JOIN PRODUCTYPE pt2 ON p2.PRODUCT_TYPE_ID = pt2.ID
;

SELECT a.*
FROM ACCOUNTS a 
JOIN PRODUCTS p ON a.PRODUCT_REF = p.ID 
JOIN PRODUCTYPE pt ON p.PRODUCT_TYPE_ID = pt.ID 
JOIN 
	(
	SELECT ID 
	FROM CLIENTS c 
	WHERE ID NOT IN 
		(
		SELECT UNIQUE c2.ID
		FROM CLIENTS c2
		JOIN PRODUCTS p2 ON c2.ID = p2.CLIENT_REF
		JOIN PRODUCTYPE pt2 ON p2.PRODUCT_TYPE_ID = pt2.ID
		WHERE pt2.NAME LIKE 'йпедхр'
		)
	) c 
ON a.CLIENT_REF = c.ID
WHERE pt.NAME LIKE 'деонгхр';