SELECT c.*
FROM CLIENTS c 
JOIN ACCOUNTS a ON a.CLIENT_REF = c.ID
WHERE a.ID IN (
	SELECT a.ID
	FROM ACCOUNTS a
	JOIN PRODUCTS p ON a.PRODUCT_REF = p.ID
	JOIN PRODUCTYPE pt ON p.PRODUCT_TYPE_ID = pt.ID
	JOIN RECORDS r ON r.ACC_REF = a.ID 
	WHERE pt.NAME = 'ÊÐÅÄÈÒ'
	GROUP BY a.ID
	HAVING SUM(r.DT) > 1
);