SELECT pt.NAME, avg(r.SUM)
FROM RECORDS r 
JOIN ACCOUNTS a ON r.ACC_REF = a.ID 
JOIN PRODUCTS p ON a.PRODUCT_REF = p.ID 
JOIN PRODUCTYPE pt ON p.PRODUCT_TYPE_ID = pt.ID
WHERE r.OPEN_DATE = TO_DATE('09.09.2019', 'DD.MM.YYYY')
GROUP BY pt.ID, pt.NAME;