UPDATE PRODUCTS p
SET p.CLOSE_DATE = CURRENT_DATE 
WHERE p.ID IN
(
	SELECT p.ID
	FROM PRODUCTS p
	JOIN ACCOUNTS a ON a.PRODUCT_REF = p.ID 
	JOIN PRODUCTYPE pt ON p.PRODUCT_TYPE_ID = pt.ID
	WHERE pt.NAME LIKE 'ÊÐÅÄÈÒ' AND a.SALDO >= 0
);
COMMIT;
