UPDATE PRODUCTYPE pt
SET pt.END_DATE = CURRENT_DATE 
WHERE pt.ID NOT IN 
(
	SELECT pt.ID
	FROM PRODUCTYPE pt
	JOIN PRODUCTS p ON p.PRODUCT_TYPE_ID = pt.ID 
	JOIN ACCOUNTS a ON a.PRODUCT_REF = p.ID 
	JOIN RECORDS r ON r.ACC_REF = a.ID 
	WHERE ADD_MONTHS(r.OPEN_DATE, 1) > CURRENT_DATE 
	GROUP BY pt.ID
);  

COMMIT;