ALTER TABLE PRODUCTS
ADD CONTRACT_SUM NUMBER(10);

COMMIT;

UPDATE PRODUCTS p
SET CONTRACT_SUM =
(
	SELECT MAX(r.SUM)
	FROM ACCOUNTS a
	JOIN RECORDS r ON r.ACC_REF = a.ID
	JOIN PRODUCTS p2 ON a.PRODUCT_REF = p2.ID
	JOIN PRODUCTYPE pt ON p2.PRODUCT_TYPE_ID = pt.ID 
	WHERE pt.NAME = 'йпедхр' AND r.DT = 1 AND p.ID = p2.ID
)
WHERE EXISTS 
(
	SELECT *
	FROM PRODUCTS p2
	JOIN PRODUCTYPE pt ON p2.PRODUCT_TYPE_ID = pt.ID 
	WHERE pt.NAME = 'йпедхр'
	AND p.ID = p2.ID
);


UPDATE PRODUCTS p
SET CONTRACT_SUM =
(
	SELECT MAX(r.SUM)
	FROM ACCOUNTS a
	JOIN RECORDS r ON r.ACC_REF = a.ID
	JOIN PRODUCTS p2 ON a.PRODUCT_REF = p2.ID
	JOIN PRODUCTYPE pt ON p2.PRODUCT_TYPE_ID = pt.ID 
	WHERE (pt.NAME = 'деонгхр' OR pt.NAME = 'йюпрю') AND r.DT = 0 AND p.ID = p2.ID
)
WHERE EXISTS 
(
	SELECT *
	FROM PRODUCTS p2
	JOIN PRODUCTYPE pt ON p2.PRODUCT_TYPE_ID = pt.ID 
	WHERE (pt.NAME = 'деонгхр' OR pt.NAME = 'йюпрю') AND p.ID = p2.ID
);

COMMIT;
